apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
        - name: user-api
          image: "glaptev8/user-api:v0.0"
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              value: "r2dbc:pool:postgres://postgres-service:5432/user_api"
            - name: FLYWAY_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/user_api"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: user-api-service
spec:
  selector:
    app: user-api
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer